set_property SRC_FILE_INFO {cfile:F:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/constrs_1/new/llrf3p0_digitizer_const.xdc rfile:../../../llrf3p0_digitizer.srcs/constrs_1/new/llrf3p0_digitizer_const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G17 IOSTANDARD LVCMOS25 DRIVE 12 SLEW SLOW } [get_ports { pwr_sync }]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS25 DRIVE 12 SLEW SLOW } [get_ports { pwr_en }]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R4 IOSTANDARD LVCMOS33 } [get_ports { sysclk }]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G4 IOSTANDARD LVCMOS15 } [get_ports { cpu_resetn }]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[0] }]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[1] }]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[2] }]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[3] }]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V15 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[4] }]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W16 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[5] }]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W15 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[6] }]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y13 IOSTANDARD LVCMOS25 } [get_ports { gpio_led[7] }]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS25} [get_ports {set_vadj[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS25} [get_ports {set_vadj[1]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS25} [get_ports vadj_en]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L19 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { lmk_sda }]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L20 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { lmk_scl }]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16 IOSTANDARD LVCMOS25} [get_ports { AD9781_sdo }]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L15 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { AD9781_rst }]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L14 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { AD9781_ncs }]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J17 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { AD9781_sclk }]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K16 IOSTANDARD LVCMOS25 DRIVE 12 SLEW FAST } [get_ports { AD9781_sdio }]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D17 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dac_dco_p }]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C17 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dac_dco_n }]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B17  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_dci_p }]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_dci_n }]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[0] }]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A16   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[0] }]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[1] }]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[1] }]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A13  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[2] }]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[2] }]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E13  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[3] }]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E14  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[3] }]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C13   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[4] }]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B13   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[4] }]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C14  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[5] }]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C15  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[5] }]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B15   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[6] }]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B16   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[6] }]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F16   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[7] }]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E17   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[7] }]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B20   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[8] }]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A20   IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[8] }]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E19  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[9] }]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19 IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[9] }]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F18  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[10] }]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[10] }]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B21  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[11] }]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A21  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[11] }]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E21  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[12] }]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D21  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[12] }]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A18  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_p[13] }]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A19  IOSTANDARD LVDS_25 DIFF_TERM FALSE } [get_ports { dac_d_n[13] }]
