# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_mp2iq_debug.xci
# IP: The module: 'ila_mp2iq_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_mp2iq_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_mp2iq_debug.xci
# IP: The module: 'ila_mp2iq_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Bachiman_FDrive/Projects/LLRF_EIC/nexys_digilent_llrf/llrf3p0_digitizer/llrf3p0_digitizer.srcs/sources_1/ip/ila_mp2iq_debug/ila_mp2iq_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_mp2iq_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
